# Copyright (c) 2008 Joakim Kolsjö, Anders Asplund and Johan Larsson
# 
# This software is provided 'as-is', without any express or implied warranty.
# In no event will the authors be held liable for any damages arising from
# the use of this software.
# 
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:
# 
# 1. The origin of this software must not be misrepresented; you must
#    not claim that you wrote the original software. If you use this
#    software in a product, an acknowledgment in the product documentation
#    would be appreciated but is not required.
# 2. Altered source versions must be plainly marked as such, and must not
#    be misrepresented as being the original software.
# 3. This notice may not be removed or altered from any source distribution.

require File.dirname(__FILE__) + '/source/deploy.rb'

desc 'Creates a .zip that only includes the game essentials (in ../../../Release)'
task :deploy do
  if Dir.pwd[1..1] == ':'
    puts 'You must run this in cygwin'  
  else
    Deploy.run
  end  
end

desc 'Creates a .zip from the version specified in source/version.rb'
task :deploy_version do
  if Dir.pwd[1..1] == ':'
    puts 'You must run this in cygwin'  
  else
    require '../../source/version.rb'
    Deploy.run($VERSION)
  end  
end
